version: '3.4'
services:
  nginx:
    image: frontend
    pull_policy: always
    ports:
      - "80:80"
  backend:
    image: backend
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test_db
      - POSTGRES_PASSWORD=test_password